algoritmo "PASSO 02 - CONDIÇÕES BÁSICAS"
// 20) Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
// ÍMPAR.
// Autor :Camila Endlich Pimenta
// Data : 18/12/2022
var
   num: Inteiro
   
inicio
      Escreva("Digite um numero: ")
      Leia(num)
      
      Se (num%2=0) entao
         Escreva(num," eh PAR")
      senao
           Escreva(num," eh IMPAR")
      FimSe
fimalgoritmo
