algoritmo "PASSO 06 – REPETIÇÃO COM FAÇA ENQUANTO"
// 61) Crie um programa que mostre na tela a seguinte contagem, usando a estrutura
// “faça enquanto”
// 0 3 6 9 12 15 18 21 24 27 30 Acabou!
// Autor : Camila Endlich Pimenta
// Data : 23/01/2023

var
   i: Inteiro
inicio
      i <- 0
      Enquanto (i <= 30) faca
               Escreva(i)
               i <- i + 3
      FimEnquanto
      Escreva(" Acabou!")
fimalgoritmo
