algoritmo "PASSO 04 – REPETIÇÕES ENQUANTO"
// 46) Crie um programa que calcule e mostre na tela o resultado da soma entre
// 6 + 8 + 10 + 12 + 14 + ... + 98 + 100.
// Autor :
// Data : 14/01/2023
// Seção de Declarações 
var
   c, s: Inteiro
inicio
c <- 6
      Enquanto (c <= 100) faca
               Escreva(c)
               s <- s + c
               c <- c + 2
      FimEnquanto
      Escreval()
      Escreva("soma: ", s)
fimalgoritmo
