algoritmo "PASSO 01 - SEQUÊNCIAS BÁSICAS"
// 2) Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela:
// Ex:
// Qual é o seu nome? João da Silva
// Olá João da Silva, é um prazer te conhecer!
// Autor : Camila Endlich Pimenta
// Data : 23/01/2023

var
   name: Caractere
inicio
      Escreva("Qual é seu nome? ")
      Leia(name)
      Escreva("Olá ", name,", é um prazer te conhecer!")
fimalgoritmo
