algoritmo "PASSO 08 – VETORES"
// 76) Crie um programa que preencha automaticamente um vetor numérico com 7
// números gerados aleatoriamente pelo computador e depois mostre os valores
// gerados na tela.
// Autor :
// Data : 28/01/2023
// Seção de Declarações 
var
   i: Inteiro
   num: vetor[1..7] de Inteiro
inicio
      Para i <- 1 ate 7 faca
           Aleatorio 1, 100
           Leia(num[i])
           Aleatorio off
      FimPara
fimalgoritmo
